import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { createSession } from "./actions";
import { ModalProvider } from "./components/common/modal";
import AuthenticationProvider from "./core/providers/auth-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   await createSession();

  return (
    <html lang="fa-IR" dir="rtl">
      <body
      >
        <AuthenticationProvider>
          <ModalProvider>
            <Toaster />
            {children}
          </ModalProvider>
        </AuthenticationProvider>
      </body>
    </html>
  );
}
